---
version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Testing
          command: yarn test
      - run:
          name: Uploading to codecov
          command: bash <(curl -s https://codecov.io/bash)
  node-10:
    <<: *test
    docker:
      - image: node:10
  node-latest-windows:
    executor:
      name: win/default
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
          shell: bash.exe
      - run:
          name: Testing
          command: yarn test
          shell: bash.exe
      - run:
          name: Uploading to codecov
          command: bash <(curl -s https://codecov.io/bash)
          shell: bash.exe
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "skuid-sfdx":
    jobs:
      - node-latest
      - node-10
      - node-latest-windows
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
